#!/usr/bin/env groovy

def gv

pipeline {
    agent any
    tools {
        nodejs 'node'
    }
    environment {
        DOCKER_HUB_ID = "karosi12"
    }
    stages {

        stage("init") {
            steps {
                script {
                    sh "ls -la"
                    gv = load "jenkins/jenkins-exercises/script.groovy"
                }
            }
        }
        stage("increment version") {
            steps {
                script {
                    gv.incrementVersion()
                }
            }
        }
        stage("Build and push image") {
            steps {
                script {
                    gv.buildAndPushDockerImage()
                }
            }
        }
        
    }     
}